FROM ruby:2.5-stretch
RUN apt-get update -qq && apt-get install -y build-essential vim netcat apt-transport-https apt-utils curl postgresql-server-dev-all libpq-dev git-core
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y yarn

RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apt-get install -y nodejs

RUN mkdir -p /app
# RUN chown -R root:root /app

WORKDIR /app

COPY . /app

RUN mkdir -p ~/.bundle
RUN mkdir -p /app/node_modules
COPY .bundle/config ~/.bundle/config

RUN bundle install --path vendor/bundle
RUN mkdir -p /app/node_modules

EXPOSE 3000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["cmd.sh"]
